### ISSUE TITLE
Failed to start with gradlew

### ISSUE THREAD

**Issue by baardl** [gostevning/telia-spring-boot#1]
Hi.

I tried to follow the instructions in the REAME.md.

`./gradlew app:bootRun
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain`

Might the error be caused by something like this? https://www.mkyong.com/gradle/jenkins-could-not-find-gradlewrappermain/

Thanks
Bård

**Comment by gostevning** [comment]
Yeah, pretty old and outdated client for Telia Identity made during a hackaton ;)

But you are right about it not starting, found that I by mistake "gitignored" the gradle directory.

Will look into fixing it up among other stuff, but if you need a working example, see https://identity.developer.telia.io/reference#tutorial which links to https://github.com/TeliaSoneraNorge/telia-simple-app

**Comment by gostevning** [comment]
Fixed so that it starts. But as stated, the client is old and outdated, so can't give any assurances that it will work even with the correct secrets and stuff in the keycloak.json
